//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_ID { get; set; }
        public Nullable<bool> Employee { get; set; }
        public Nullable<bool> Visitor { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
    }
}
